- src/main/java/org/jboss/msc/service/ServiceTargetImpl.java
To backport to EAP 6.4.z.
https://bugzilla.redhat.com/show_bug.cgi?id=1401506
master and 1.2 branches already have the fix but there is no JIRA ticket.
> proper synchronization to prevent ConcurrentModificationException during traversal

- src/main/java/org/jboss/msc/service/ServiceControllerImpl.java
- src/main/java/org/jboss/msc/service/ServiceRegistrationImpl.java
All commits in this first PR are preserving current behaviour.
> First round of refactorings

- src/main/java/org/jboss/msc/service/ServiceContainerImpl.java
- src/main/java/org/jboss/msc/service/ServiceControllerImpl.java
- src/test/java/org/jboss/msc/service/DependencyCycleTestCase.java
- src/test/resources/org/jboss/msc/racecondition/ChildServicesWithOptionalDependenciesTestCase.btm
- src/test/resources/org/jboss/msc/racecondition/ClearRemoveRequestOnDownServiceTestCase.btm
- src/test/resources/org/jboss/msc/racecondition/ClearRemoveRequestOnRemovingServiceTestCase.btm
- src/test/resources/org/jboss/msc/racecondition/CycleWithCancelledServiceTestCase.btm
- src/test/resources/org/jboss/msc/racecondition/DependencyFailureClearedToCancelledServiceTestCase.btm
- src/test/resources/org/jboss/msc/racecondition/NewDependentOfFailingServiceTestCase.btm
- src/test/resources/org/jboss/msc/racecondition/StopRequestedToUpTransitionTestCase.btm
The purpose of this PR is to prepare common base for all tasks.
> A dozen of refactorings plus one enhancement

- pom.xml
https://issues.jboss.org/browse/MSC-243
> [MSC-243] Fixing wrong Java SE 8 API docs link

- src/main/java/org/jboss/msc/service/ServiceContainerImpl.java
- src/main/java/org/jboss/msc/service/ServiceRegistrationImpl.java
We cannot remove dependency registration from CONTAINER registry
if there are some dependent services in the process of installation.
https://issues.jboss.org/browse/MSC-245
> [MSC-245] Proper fix for CONTAINER registry memory leak.

- src/main/java/org/jboss/msc/service/ServiceContainerImpl.java
- src/main/java/org/jboss/msc/service/ServiceControllerImpl.java
- src/main/java/org/jboss/msc/service/ServiceRegistrationImpl.java
- src/main/java/org/jboss/msc/service/WritableValueImpl.java
https://issues.jboss.org/browse/MSC-247
https://issues.jboss.org/browse/MSC-248
https://issues.jboss.org/browse/MSC-250
> A couple of MSC 1.4 fixes

- src/main/java/org/jboss/msc/service/ServiceContainerImpl.java
- src/main/java/org/jboss/msc/service/ServiceControllerImpl.java
- src/main/java/org/jboss/msc/service/ServiceRegistrationImpl.java
- src/main/java/org/jboss/msc/service/WritableValueImpl.java
https://issues.jboss.org/browse/MSC-247
https://issues.jboss.org/browse/MSC-248
https://issues.jboss.org/browse/MSC-250
> A couple of MSC master fixes

- src/main/java/org/jboss/msc/service/ServiceBuilder.java
- src/main/java/org/jboss/msc/service/ServiceBuilderImpl.java
https://issues.redhat.com/browse/MSC-256
> [MSC-256] Fix ServiceBuilder javadoc

- src/main/java/org/jboss/msc/service/ServiceContainerImpl.java
https://issues.redhat.com/browse/MSC-257
This is the upstream version of: https://github.com/jboss-msc/jboss-msc/pull/92
> [MSC-257] Unregistering container's WeakReference from shutdown hook containers set on shutdown

- src/main/java/org/jboss/msc/service/ServiceContainer.java
- src/main/java/org/jboss/msc/service/ServiceContainerImpl.java
- src/main/java/org/jboss/msc/service/ServiceLogger.java
https://issues.redhat.com/browse/MSC-258
> [MSC-258] Use one shutdown hook per container and let the JVM keep track of them

- src/main/java/org/jboss/msc/service/ServiceControllerImpl.java
- src/main/java/org/jboss/msc/service/StabilityMonitor.java
- src/main/java/org/jboss/msc/service/Substate.java
- src/main/java/org/jboss/msc/service/Transition.java
https://issues.redhat.com/browse/MSC-309
> Simplifying state machine

- src/main/java/org/jboss/msc/service/DelegatingServiceContainer.java
- src/main/java/org/jboss/msc/service/DelegatingServiceTarget.java
- src/main/java/org/jboss/msc/service/ServiceTarget.java
- src/main/java/org/jboss/msc/service/ServiceTargetImpl.java
https://issues.redhat.com/browse/MSC-322
https://issues.redhat.com/browse/MSC-323
https://issues.redhat.com/browse/MSC-324
https://issues.redhat.com/browse/MSC-325
https://issues.redhat.com/browse/MSC-326
https://issues.redhat.com/browse/MSC-327
> Deprecated API Cleanup - Fourth Round

- CODEOWNERS
https://issues.redhat.com/browse/MSC-315
> [MSC-315] Adding CODEOWNERS file

- src/main/java/org/jboss/msc/service/DelegatingServiceContainer.java
- src/main/java/org/jboss/msc/service/DelegatingServiceController.java
- src/main/java/org/jboss/msc/service/DelegatingServiceTarget.java
- src/main/java/org/jboss/msc/service/ServiceBuilderImpl.java
- src/main/java/org/jboss/msc/service/ServiceContainerImpl.java
- src/main/java/org/jboss/msc/service/ServiceController.java
- src/main/java/org/jboss/msc/service/ServiceControllerImpl.java
- src/main/java/org/jboss/msc/service/ServiceTarget.java
- src/main/java/org/jboss/msc/service/ServiceTargetImpl.java
- src/main/java/org/jboss/msc/service/management/ServiceStatus.java
https://issues.redhat.com/browse/MSC-334
https://issues.redhat.com/browse/MSC-335
https://issues.redhat.com/browse/MSC-336
https://issues.redhat.com/browse/MSC-337
> Enhancements for 1.5 branch

- src/main/java/org/jboss/msc/service/DelegatingServiceContainer.java
- src/main/java/org/jboss/msc/service/DelegatingServiceController.java
- src/main/java/org/jboss/msc/service/DelegatingServiceTarget.java
- src/main/java/org/jboss/msc/service/ServiceBuilderImpl.java
- src/main/java/org/jboss/msc/service/ServiceContainerImpl.java
- src/main/java/org/jboss/msc/service/ServiceController.java
- src/main/java/org/jboss/msc/service/ServiceControllerImpl.java
- src/main/java/org/jboss/msc/service/ServiceTarget.java
- src/main/java/org/jboss/msc/service/ServiceTargetImpl.java
- src/main/java/org/jboss/msc/service/management/ServiceStatus.java
https://issues.redhat.com/browse/MSC-334
https://issues.redhat.com/browse/MSC-335
https://issues.redhat.com/browse/MSC-336
https://issues.redhat.com/browse/MSC-337
Downstream PR: https://github.com/jboss-msc/jboss-msc/pull/108
> Enhancements for main branch

- src/main/java/org/jboss/msc/service/ServiceControllerImpl.java
- src/main/java/org/jboss/msc/service/management/ServiceStatus.java
https://issues.redhat.com/browse/MSC-339
> MSC-339 ServiceController.dumpServices() throws NPE if service has no identifier

- pom.xml
https://issues.redhat.com/browse/MSC-343
> [MSC-343] Defining automatic module name is org.jboss.msc

- .github/workflows/ci.yml
https://issues.redhat.com/browse/MSC-340
> [MSC-340] Adding JDK21 to CI matrix

- pom.xml
- src/main/java/org/jboss/msc/service/ServiceContainerImpl.java
- src/test/java/org/jboss/msc/MSC245TestCase.java
https://issues.redhat.com/browse/MSC-344
> [MSC-344] Removing dependency on JBoss Modules library

- pom.xml
- src/main/java/org/jboss/msc/service/ServiceContainerImpl.java
- src/test/java/org/jboss/msc/MSC245TestCase.java
https://issues.redhat.com/browse/MSC-344
Downstream PR: https://github.com/jboss-msc/jboss-msc/pull/131
> [MSC-344] Removing dependency on JBoss Modules

- src/main/java/org/jboss/msc/service/LeakDetectorServiceContainer.java
- src/main/java/org/jboss/msc/service/ServiceContainer.java
- src/main/java/org/jboss/msc/service/ServiceContainerImpl.java
https://issues.redhat.com/browse/MSC-147
> [MSC-147] Use java.lang.ref.Cleaner based solution instead of deprecated Object.finalize() approach

- src/main/java/org/jboss/msc/service/ServiceControllerImpl.java
https://issues.redhat.com/browse/MSC-346
> MSC-346 ServiceStatus throws NPE if parent controller is anonymous

- src/main/java/org/jboss/msc/service/ServiceControllerImpl.java
https://issues.redhat.com/browse/MSC-346
Upstream PR: https://github.com/jboss-msc/jboss-msc/pull/141
> [MSC-346] ServiceStatus throws NPE if parent controller is anonymous
